branches:
  only:
  - master

os:
- linux

language: generic

git:
  depth: 99999

addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin
    ssh_known_hosts:
    - web543.webfaction.com

cache:
  apt: true
  timeout: 300
  directories:
    - $HOME/.cache/pip
    - $HOME/miniconda

services:
  - docker

before_install:
- docker build -t travis_docker . && docker run -it travis_docker

install:
- if [ "$encrypted_74d70a284b7d_key" ]; then
  openssl aes-256-cbc -K $encrypted_74d70a284b7d_key -iv $encrypted_74d70a284b7d_iv -in travis_deploy_rsa.enc -out /tmp/travis_deploy_rsa -d;
  eval "$(ssh-agent -s)";
  chmod 600 /tmp/travis_deploy_rsa;
  ssh-add /tmp/travis_deploy_rsa;
  echo -e "Host web543.webfaction.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config;
fi
